"""initial schema

Revision ID: f3b4661263f3
Revises:
Create Date: 2026-09-28 12:48:22.629146

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3b4661263f3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buoy",
        sa.Column("id", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("latitude", sa.Double(), nullable=True),
        sa.Column("longitude", sa.Double(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "series",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("buoy_id", sa.String(length=8), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.String(), nullable=False),
        sa.Column("modified_through", sa.DateTime(timezone=True), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latest_date", sa.Date(), nullable=True),
        sa.Column("latest_temperature", sa.Double(), nullable=True),
        sa.Column("latest_climatology", sa.Double(), nullable=True),
        sa.Column("latest_threshold", sa.Double(), nullable=True),
        sa.Column("days_above", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["buoy_id"],
            ["buoy.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("buoy_id", "depth"),
        sa.UniqueConstraint("dataset_id"),
    )
    op.create_table(
        "climatology_day",
        sa.Column("series_id", sa.Integer(), nullable=False),
        sa.Column("day_of_year", sa.Integer(), nullable=False),
        sa.Column("mean", sa.Double(), nullable=False),
        sa.Column("threshold", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("series_id", "day_of_year"),
    )
    op.create_table(
        "daily_mean",
        sa.Column("series_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("temperature", sa.Double(), nullable=False),
        sa.Column("hours", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("series_id", "date"),
    )
    op.create_table(
        "event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("series_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("peak_date", sa.Date(), nullable=False),
        sa.Column("max_intensity", sa.Double(), nullable=False),
        sa.Column("mean_intensity", sa.Double(), nullable=False),
        sa.Column("category", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_event_series_id"), ["series_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_series_id"))

    op.drop_table("event")
    op.drop_table("daily_mean")
    op.drop_table("climatology_day")
    op.drop_table("series")
    op.drop_table("buoy")
    # ### end Alembic commands ###
